var GAME_LEVELS = [
  [
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                    xxxxx       ",
   "                          o                                         xx!xx       ",
   "                                                                    xx!xx       ",
   "                          x                                           v         ",
   "                      o       o                                                 ",
   "                                                                                ",
   "                     xxx     xxx                                             o  ",
   "                                                                           xxxxx",
   "                                       o  o  o  o                          xxxxx",
   "    @                                                                      xxxxx",
   "xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "         x!!!x                                                                  ",
   "         x!!!x                                                                  ",
   "         xxxxx                                                                  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
  ],
  [
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                     x          x                                             ",
   "                                                                                    x!x        x!x                                            ",
   "                                                                  xxx                v     o    v    o                       xxx              ",
   "                                                   xx      xx    xx!xx                                                      xx!xx             ",
   "                                    o o      xx                  x!!!x                    xxx       xxx                     x!!!x             ",
   "                                                                 xxvxx                                                      xxvxx             ",
   "                                   xxxxx                                            xxx        xxx       xxx                  o               ",
   "                                                                                                                                              ",
   "                                          o o                                                                                x x            o ",
   "                        o                                                                                         xxx        xox            x ",
   "                                         xxxxx                            o    xxxxxxx                                      xx xx          xx ",
   "             xxxx       o       o                                              x     x        o        o                                  xxx ",
   "     @       x  x                                                xxxxx         x     x                           x!!!x                   xxxx ",
   "xxxxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              x   x                  x     x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              xxxxx                  xxxxxxx                                                                                  ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                "
  ],
  [
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                     x          x                                             ",
   "                                                                                    x!x        x!x                                            ",
   "                                                                  xxx                v     o    v    o                       xxx              ",
   "                                                   xx      xx    xx!xx                                                      xx!xx             ",
   "                                    o o      xx                  x!!!x                    xxx       xxx                     x!!!x             ",
   "                                                                 xxvxx                                                      xxvxx             ",
   "                                   xxxxx                                            xxx        xxx       xxx                  o               ",
   "                                                                                                                                              ",
   "                                          o o                                                                                x x            o ",
   "                        o                                                                                         xxx        xox            x ",
   "                                         xxvxx                            o    xxxxxxx                                      xx xx          xx ",
   "             xxxx       o       o                                              x     x        o        o                                  xxx ",
   "     @       x  x                                                xxxxx         x     x                           x!!!x                   xxxx ",
   "xxxxxxxxvvxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                              x   x                  x     x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              xxxxx                  xxxxxxx                                                                                  ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "
  ],
  [
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                     x          x                                             ",
   "                                                                                    x!x        x!x                                            ",
   "                                                                  xxx                v     o    v    o                       xxx              ",
   "                                                   xx      xx    xx!xx                                                      xx!xx             ",
   "                                    o o      xx                  x!!!x                    xxx       xxx                     x!!!xxxxx!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx             ",
   "                                                                 xxvxx                                                      xxvxx             ",
   "                                   xxxxx                                            xxx        xxx       xxx                  o               ",
   "                                                                                                                                              ",
   "                                          o o                                                                                x x            o ",
   "                        o                                                                                         xxx        xox            x ",
   "                                         xxvxx                            o    xxxxxxx                                      xx xx          xxxxxxxxxxxxxxxxxxxxxxxxx ",
   "             xxxx       o       o                                              x     x        o        o                                  xxx ",
   "     @       x vx                         00                       xxxxx         x     x                           x!!!x                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx00 ",
   "vxxxxxxxvvxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                              x   x                  x     x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              x!!!x                  x!!!!!x                                                                                  ",
   "                              xxxxx                  xxxxxxx                                                                                  ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "
  ],
  [
   "                                                                                                                                              ",
   "xxxxxx  xxxx                                                                                                                                            ",
   "x!!!!x  x!!x                                                                                                                                 ",
   "x!!!!x  x!!x                                                                                                                                         ",
   " vvvv    vv                                                                                                                                           ",
   "                                                                                                                                          ",
   "                     !  !               x!                                                                                                   ",
   "                     x  x              xx                                                                        ",
   "      @              xooxo xo         xxxo                                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                          xxxx                                                                 ",
   "                                                xx              !                                                            x!!!!!!!xxxxxxo        ",
   "                                                xxxo            x                                                                                           ",
   "                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                            ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
   "                                                                                                                                              ",
  ]
];
